CREATE TABLE IF NOT EXISTS APP_USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(100) NOT NULL,
    PERMISSIONS VARCHAR(200),
    ACTIVE_SESSION_TOKEN VARCHAR(64),
    SESSION_LAST_ACTIVITY_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PERMISSIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    LABEL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_PERMISSIONS (
    USER_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, PERMISSION_ID)
);

CREATE TABLE IF NOT EXISTS ACCOUNTING_ENTRIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ENTRY_DATE DATE NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(80) NOT NULL,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(100),
    MEMO VARCHAR(255),
    USER_ID BIGINT
);

CREATE TABLE IF NOT EXISTS ACCOUNTING_BALANCES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AS_OF_DATE DATE NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    ACCOUNT_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(80) NOT NULL,
    AMOUNT DECIMAL(14, 2) NOT NULL,
    REPAYMENT_DAY INT,
    REPAYMENT_ACCOUNT_NAME VARCHAR(100),
    LAST_REPAYMENT_DATE DATE,
    MEMO VARCHAR(255),
    USER_ID BIGINT
);

CREATE TABLE IF NOT EXISTS JAPANESE_WORDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WORD VARCHAR(80) NOT NULL,
    READING VARCHAR(100) NOT NULL,
    MEANING_ZH VARCHAR(160) NOT NULL,
    PART_OF_SPEECH VARCHAR(40) NOT NULL,
    CATEGORY VARCHAR(60) NOT NULL,
    LEVEL_NAME VARCHAR(20) NOT NULL,
    EXAMPLE_JA VARCHAR(500) NOT NULL,
    EXAMPLE_ZH VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS JAPANESE_WORD_PROGRESS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    WORD_ID BIGINT NOT NULL,
    MASTERY_STATUS VARCHAR(20) NOT NULL,
    REVIEW_COUNT INT NOT NULL,
    NEXT_REVIEW_DATE DATE,
    LAST_REVIEWED_AT TIMESTAMP,
    UNIQUE (USER_ID, WORD_ID)
);

CREATE TABLE IF NOT EXISTS JAPANESE_QUIZ_QUESTIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_TYPE VARCHAR(40) NOT NULL,
    PROMPT VARCHAR(500) NOT NULL,
    OPTION_A VARCHAR(200) NOT NULL,
    OPTION_B VARCHAR(200) NOT NULL,
    OPTION_C VARCHAR(200) NOT NULL,
    OPTION_D VARCHAR(200) NOT NULL,
    CORRECT_OPTION VARCHAR(1) NOT NULL,
    EXPLANATION VARCHAR(500) NOT NULL,
    CATEGORY VARCHAR(60) NOT NULL,
    LEVEL_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS JAPANESE_QUIZ_RESULTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    QUESTION_ID BIGINT NOT NULL,
    SELECTED_OPTION VARCHAR(1) NOT NULL,
    CORRECT BOOLEAN NOT NULL,
    ANSWERED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS JAPANESE_KNOWLEDGE_ARTICLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE_JA VARCHAR(200) NOT NULL,
    TITLE_ZH VARCHAR(200) NOT NULL,
    CONTENT_JA LONGTEXT NOT NULL,
    CONTENT_ZH LONGTEXT NOT NULL,
    TOPIC VARCHAR(80) NOT NULL,
    READING_MINUTES INT NOT NULL
);

CREATE TABLE IF NOT EXISTS STOCK_TRADES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TRADE_YEAR INT NOT NULL,
    TRADE_DATE DATE NOT NULL,
    STOCK_NAME VARCHAR(100) NOT NULL,
    SOURCE_LABEL VARCHAR(120) NOT NULL,
    BUY_QUANTITY DECIMAL(18, 4),
    BUY_PRICE DECIMAL(18, 4),
    BUY_GROSS_AMOUNT DECIMAL(18, 4),
    BUY_FEE DECIMAL(18, 4),
    BUY_TOTAL_AMOUNT DECIMAL(18, 4),
    SELL_QUANTITY DECIMAL(18, 4),
    SELL_PRICE DECIMAL(18, 4),
    SELL_GROSS_AMOUNT DECIMAL(18, 4),
    SELL_FEE DECIMAL(18, 4),
    SELL_NET_AMOUNT DECIMAL(18, 4),
    PROFIT_LOSS DECIMAL(18, 4),
    BUY_MULTIPLIER DECIMAL(10, 6),
    SELL_MULTIPLIER DECIMAL(10, 6),
    SOURCE_ROW_NUMBER INT NOT NULL
);
